---
- name: Postgresql | configure postgres | ensure postgresql service is stopped
  ansible.builtin.systemd:
    name: "postgresql-{{ postgres_version }}"
    state: stopped

- name: Postgresql | configure postgres | move default pg_hba.conf on first install
  ansible.builtin.command:
    cmd: mv /var/lib/pgsql/{{ postgres_version }}/data/pg_hba.conf /var/lib/pgsql/{{ postgres_version }}/data/pg_hba.conf.default
    removes: /var/lib/pgsql/{{ postgres_version }}/data/pg_hba.conf
  when: not pgdata_version.stat.exists

- name: Postgresql | configure postgres | configure pg_hba
  community.postgresql.postgresql_pg_hba:
    dest: /var/lib/pgsql/{{ postgres_version }}/data/pg_hba.conf
    contype: "{{ item.contype }}"
    users: "{{ item.users }}"
    source: "{{ item.source | default(omit) }}"
    databases: "{{ item.databases }}"
    method: "{{ item.method }}"
    create: true
    owner: postgres
    group: postgres
    mode: "0600"
  loop: "{{ pg_hba_user_options }}"
  notify:
    - Reload postgresql

- name: Postgresql | configure postgres | configure postgresql-config
  ansible.builtin.template:
    src: postgresql.conf.j2
    dest: /var/lib/pgsql/{{ postgres_version }}/data/postgresql.conf
    owner: postgres
    group: postgres
    mode: "0600"
  notify:
    - Restart postgresql

- name: Postgresql | configure postgres | ensure postgresql service is started and enabled
  ansible.builtin.systemd:
    name: "postgresql-{{ postgres_version }}"
    state: started
    enabled: true
