---
- name: Postgres | init_postgres | check if database is already initialized
  ansible.builtin.stat:
    path: /var/lib/pgsql/{{ postgres_version }}/data/PG_VERSION
  register: pgdata_version

- name: Postgres | init_postgres | init database
  ansible.builtin.command: /usr/pgsql-{{ postgres_version }}/bin/postgresql-{{ postgres_version }}-setup initdb
  when: not pgdata_version.stat.exists
  notify:
    - Start postgresql
