---
- name: Converge
  hosts: all
  tasks:
    - name: "Include ansible_postgresql"
      ansible.builtin.include_role:
        name: "ansible_postgresql"
      vars:
        pg_config_listen_addresses: '*'
        pg_hba_user_options:
        - contype: host
          users: all
          source: 127.0.0.1/32
          databases: all
          method: md5
        - contype: host
          users: all
          source: 10.10.10.0/24
          databases: all
          method: md5
