---
- name: Converge
  hosts: all
  become: yes
  roles:
    - role: ansible-postgresql
      pg_config_listen_addresses: '*'
      pg_hba_user_options:
      - contype: host
        users: all
        source: 127.0.0.1/32
        databases: all
        method: md5
      - contype: host
        users: all
        source: 10.110.0.0/24
        databases: all
        method: md5