- name: install base packages
  hosts: all
  gather_facts: false
  tasks:
    - name: molecule | prepare | bootstrap python3
      ansible.builtin.raw: |
        command -v python3 || dnf install -y python3
      changed_when: false

    - name: molecule | prepare | install epel
      ansible.builtin.package:
        name:
          - epel-release

    - name: molecule | prepare | install base packages
      ansible.builtin.package:
        name:
          - tar
          - gzip
          - unzip
          - xz
          - bzip2
          - python3
          - nc
          - bind-utils
          - htop
          - vim
          - glibc-langpack-en
          - net-tools
        state: present