- name: install base packages
  hosts: all
  tasks:
    # Make sure the default MySQL and SQLite
    # schemas are installed in /usr/share/doc/
    - name: molecule | prepare | install epel
      package:
        name:
          - epel-release
    - name: molecule | prepare | install base packages
      package:
        name:
          - tar
          - gzip
          - unzip
          - xz
          - bzip2
          - python3
          - nc
          - bind-utils
          - htop
          - vim
          - glibc-langpack-en
          - net-tools
        state: present