---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  vars:
    ansible_python_interpreter:
  tasks:
  - name: Verify | check postgres is running
    ansible.builtin.systemd:
      name: postgresql-13.service
      state: started
