---
- name: Postgres | extension | postgis | enable CRB/PowerTools repository
  ansible.builtin.command: >
    dnf config-manager --set-enabled
    {{ 'crb' if ansible_distribution_major_version | int >= 9 else 'powertools' }}
  changed_when: false

- name: Postgres | extension | postgis | install postgis
  ansible.builtin.dnf:
    name:
      - postgis{{ postgis_version }}_{{ postgres_version }}
    state: present
  notify:
    - Restart postgresql
